#!/usr/bin/env python

"""
Namelist creator for E3SM's DEMSI component
"""

import os, sys

_CIMEROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..","..","..","cime")
sys.path.append(os.path.join(_CIMEROOT, "scripts", "Tools"))

from standard_script_setup import *
from CIME.case import Case
from CIME.utils import expect, run_cmd_no_fail, safe_copy
from CIME.buildnml import create_namelist_infile, parse_input

logger = logging.getLogger(__name__)

###############################################################################
def buildnml(case, caseroot, compname):
###############################################################################
    expect(compname == "demsi", compname)

    os.chdir(caseroot)

    cimeroot         = case.get_value("CIMEROOT")
    caseroot         = case.get_value("CASEROOT")
    casebuild        = case.get_value("CASEBUILD")
    casename         = case.get_value("CASE")
    srcroot          = case.get_value("SRCROOT")
    din_loc_root     = case.get_value("DIN_LOC_ROOT")
    ice_grid         = case.get_value("ICE_GRID")
    ice_mask         = case.get_value("MASK_GRID")
    ice_pio_typename = case.get_value("ICE_PIO_TYPENAME")
    #ninst_ice       = case.get_value("NINST_ICE")
    ninst_ice        = 1 # Change if you want multiple instances... though this isn't coded yet.
    ninst_ice_real   = case.get_value("NINST_ICE")
    ntasks_ice       = case.get_value("NTASKS_ICE")
    rundir           = case.get_value("RUNDIR")
    run_type         = case.get_value("RUN_TYPE")
    run_refcase      = case.get_value("RUN_REFCASE")
    run_refdate      = case.get_value("RUN_REFDATE")
    run_reftod       = case.get_value("RUN_REFTOD")
    ncpl_base_period = case.get_value("NCPL_BASE_PERIOD")
    atm_ncpl         = case.get_value("ATM_NCPL")

    demsiconf_dir = os.path.join(casebuild, "demsiconf")

    if not os.path.isdir(demsiconf_dir): os.mkdir(demsiconf_dir)

    # create `namelist' file
    fileNamelist = open(os.path.join(demsiconf_dir, "demsi_in"), "w")
    fileNamelist.write("DEMSI NAMELIST\n")
    fileNamelist.close()

    in_filename = "demsi_in"
    if os.path.isdir(rundir):
        safe_copy(os.path.join(demsiconf_dir, "demsi_in"), os.path.join(rundir, in_filename))

###############################################################################
def _main_func():
###############################################################################
    caseroot = parse_input(sys.argv)
    with Case(caseroot) as case:
        buildnml(case, caseroot, "demsi")

if __name__ == "__main__":
    _main_func()
